### PR TITLE
added week 3 mcq

### PR DESCRIPTION
**Pull request by bymedeu**
* **Contributing guidelines check**
- [ ] Check that this pull request follows our contributing guidelines

* **Are you adding new files?**
- [ ] Did you run the `pdfshrink.py` script on your files?

* **Comment your changes:**

I will add week 2 and week 1 lates

### CODE REVIEW

**Comment by bymedeu** [comment]
I have more docs to add too

**Comment by matiboux** [comment]
@bymedeu I compressed your files to reduce file size.

Almost ready to merge now, I have one question first:
Is the file naming a mistake or is it relevant to something I don't understand?

- I expected `mqc-2028-24-01.pdf` and `mqc-2028-24-01-corrige.pdf` to be named:
  ```diff
  -mqc-2028-24-01*.pdf
  +mcq-2028-s3-01*.pdf
  ```
- I expected `mqc-2028-24-03.pdf` to be named:
  ```diff
  -mqc-2028-24-03.pdf
  +mcq-2028-s3-03.pdf
  ```
- I expected `mqc-2028-24-30-corrige.pdf` to be named:
  ```diff
  -mqc-2028-24-30-corrige.pdf
  +mcq-2028-s3-03-corrige.pdf
  ```

**Comment by bymedeu** [comment]
Depends, i think i followed an existing naming version, with 24 being 2024 the current year. I'll update the names next weeks, as the s3 version seems better!

**Comment by bymedeu** [comment]
Names have been updated

**Comment by matiboux** [comment]
Thank you for the new files and the renaming.

> seems i force pushed by mistake, still getting used to github, mb

It's alright! That's usually how we learn.

I've restored my commit and amended it to reduce file size of newest files as well.

I'll approve this PR. Unless you have other changes to make, this will be merged shortly.

**Review by matiboux — APPROVED** [review]

**Comment by matiboux** [comment]
In that case, let's merge this PR.
I will let you open a new PR when new files are available for you to share.

**Pull request merged**
