### PR TITLE
2028 - Added all MCQs, All Exams except 1 Maths TD and Algo Finals S2

### PR DESCRIPTION
**Pull request by UwUDevv**
I added all the MCQs for the 2028 year, that is to say, Seminar, S1, S2 in english and french. I also added all exams except last TD of maths and the finals of algo.

### CODE REVIEW

**Review by matiboux — CHANGES_REQUESTED** [review]
Noticed these files are deleted:
- `S1/MCQs/2028/mcq-2028-s1-03-en.pdf`
- `S1/MCQs/2028/mcq-2028-s1-04-en.pdf`
- `S1/MCQs/2028/mcq-2028-s1-05-en.pdf`
- `S1/MCQs/2028/mcq-2028-s1-06-en.pdf`
- `S1/MCQs/2028/mcq-2028-s1-07-en.pdf`
- `S1/MCQs/2028/mcq-2028-s1-08-en.pdf`

Was that intentional?

**Comment by UwUDevv** [comment]
> Noticed these files are deleted:
> 
> * `S1/MCQs/2028/mcq-2028-s1-03-en.pdf`
> * `S1/MCQs/2028/mcq-2028-s1-04-en.pdf`
> * `S1/MCQs/2028/mcq-2028-s1-05-en.pdf`
> * `S1/MCQs/2028/mcq-2028-s1-06-en.pdf`
> * `S1/MCQs/2028/mcq-2028-s1-07-en.pdf`
> * `S1/MCQs/2028/mcq-2028-s1-08-en.pdf`
> 
> Was that intentional?

Yeah these were misplaced duplicates that are inside 'S1/MCQs/2028/en/'

**Comment by matiboux** [comment]
> Yeah these were misplaced duplicates that are inside 'S1/MCQs/2028/en/'

Oh right, nice catch! Thank you.

**Review by matiboux — APPROVED** [review]
Thank you for this huge contribution!

**Pull request merged**
