### PR TITLE
add s5-2026 Maths1 current fr corrections

### PR DESCRIPTION
**Pull request by ErwannLesech**
This commit adds a new directory called Maths1 that will include all Mathematiques1 ECUE exams. It also creates 2 folders: STA and CPXA and push all fr corrections currently available

If this pr looks good for you, I will, in the future, add other modules that are studied during S5.

### CODE REVIEW

**Review by matiboux — CHANGES_REQUESTED** [review]
I don't think the `Maths1` folder is necessary. I don't think splitting courses by their courses unit is relevant. The course code is unique and should be clear enough.

Also, note that the courses unit (such as `Maths1`) may change year after year: some get renamed, some get their syllabus changed, some get from or lose courses to other units.
Moreover, some courses unit are specific to optional or curriculum courses, some of them I had probably do not exist anymore.

The course codes should not change as often. A different course code usually mean a different course with a different content.

However, it's true that the S5+ semester folders lack a defined folders structure like one seen for the first four semesters. Could we work something out?

**Comment by ErwannLesech** [comment]
> I don't think the `Maths1` folder is necessary. I don't think splitting courses by their courses unit is relevant. The course code is unique and should be clear enough.
> 
> Also, note that the courses unit (such as `Maths1`) may change year after year: some get renamed, some get their syllabus changed, some get from or lose courses to other units. Moreover, some courses unit are specific to optional or curriculum courses, some of them I had probably do not exist anymore.
> 
> The course codes should not change as often. A different course code usually mean a different course with a different content.
> 
> However, it's true that the S5+ semester folders lack a defined folders structure like one seen for the first four semesters. Could we work something out?

I understand that in order to maintain these past exams in the long term, the use of **Course Units** is not appropriate given that they may evolve over time.

However, we would have to find an _**effective way**_ to guarantee appreciable visualization and avoid a significant quantity of course code files (25 individual courses following the syllabus) which will not change if I understand correctly.

Unlike the first four semesters, the exams only concern **one course** at a time and cannot be subdivided into MCQs, Finals or TDs. I suggest you simply divide the different courses into 3 major files:
- Harmo (It will include the first month courses with info and maths parts [8 courses code])
- Maths & Info (which will include the main subjects of the rest of the semesters [9 courses code])
- Human Science (which will include all who will support communication and company knowledge courses [8 courses])

If this is not clear enough, it would be preferable to keep the previous architecture and only put the main courses (which should lead to a **dozen** files)

**Comment by matiboux** [comment]
> I suggest you simply divide the different courses into 3 major files:
> 
> * Harmo (It will include the first month courses with info and maths parts [8 courses code])
> * Maths & Info (which will include the main subjects of the rest of the semesters [9 courses code])
> * Human Science (which will include all who will support communication and company knowledge courses [8 courses])

Interesting. What would you say about this folder patterns: `[Semester]/[Category]/[CourseCode]/`?

As for specific categories to use, what about:?
- `S5/Harmonization/[CourseCode]/`
- `[Semester]/Science/[CourseCode]/`
- `[Semester]/Humanities/[CourseCode]/`

`Harmonization` seems a long category name however, but I don't have an idea for an alternative.

**Review by matiboux — APPROVED** [review]
Thanks for the changes! Thanks for the contribution, it should be ready for merge now.

**Pull request merged**
